FROM mcr.microsoft.com/devcontainers/python:1-3.11-bookworm

USER root
RUN install -d -o vscode -g vscode -m 0755 \
    /home/vscode/.vscode-server \
    /home/vscode/.vscode-server/bin \
    /home/vscode/.vscode-server/data \
    /home/vscode/.copilot
